apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    app: {{ include "chart.fullname" . }}
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.service.annotations }}    
  annotations:
{{ toYaml . | indent 4 }}  
{{- end }}
spec: 
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    name: http
    targetPort: http
  selector:
    app: {{ include "chart.fullname" . }}
    release: {{ .Release.Name }}